# --- robotlist.toml ---
#
# Robot-specific configuration includes

[robotconfig]
file_rev = 1          # robotlist.toml file revision
robot_name = "sim"    # Name of this robot
version_name = "sim"  # Required version name checked against versionlist.toml

# -- Motor assignments and indices etc.

# -- Override definitions for parameters defined in default or version directories
%include overrides.toml

# -- Simulation configuration for MuJoCo physics environment
%include simulation.toml
