# --- robotlist.toml ---
#
# Robot-specific configuration includes

[robotconfig]
file_rev = 1                # robotlist.toml file revision
robot_name = "go1r1"  # Name of this robot
version_name = "go1"  # Required version name checked against versionlist.toml

# -- Motor assignments and indices etc.

# -- Override definitions for parameters defined in default or version directories
%include overrides.toml

# -- Simulation configuration for MuJoCo physics environment
%include go1.toml
