# --- versionlist.toml ---
#
# Version-specific configuration values and includes

[versionconfig]
file_rev = 3          # versionlist.toml file revision
version_name = "sim"  # Name of the version to be checked against robotlist.toml

%include threads.toml # Thread configuration (currently empty for sim)

