/* 
 * Copyright (C) 2005-2025 Uluç Saranlı. All Rights Reserved
 * 
 * This file is part of the RoboMETU robot control software library
 * collection. Unauthorized copying of this file, via any medium is
 * strictly prohibited.
*/

#ifndef WALKMODULE_HH
#define WALKMODULE_HH

#include <vector>
#include "rtcore/Module.hh"

#include "Eigen/Dense"

class MdlLegControl;
class QuadrupedKinematics;

namespace rtcore {
  class Profiler;
}

#define WALKMODULE_NAME "MdlDrawSquare"

/** \brief Behavioral module that implements a rectangular body trajectory 

  This module implements a simple rectangular body motion by commanding all legs
  to draw identical rectanges under their respective hips. The trajectory is
  generated by using the Profiler class, and individual legs are commanded to
  follow the trajectory by using the MdlLegControl module through inverse
  kinematics.

  Note that this module also implements an example of a state machine with three
  states: WAIT, PREPLEGS, and DRAWSQUARE. The WAIT state is inhabited for a
  certain duration, followed by the PREPLEGS state, which prepares the legs to
  go to the initial corner of the rectangular trajectory from their current
  positions. Finally, the DRAWSQUARE state is entered, which commands the legs
  to indefinitely follow the periodic, rectangular trajectory.

  Finally, this module also demonstrates configuration through TOML files, with
  entries under the [drawsquare] table configuring various aspects of the
  behavior parametrically.
  
 */
class MdlDrawSquare : public rtcore::Module {
public:
  MdlDrawSquare( );
  ~MdlDrawSquare();

  void init();
  void uninit();
  void activate();
  void deactivate();
  void update();

private:

  enum class _state_t {
    WAIT,
    PREPLEGS,
    DRAWSQUARE,
    DONE
  };
  _state_t _state = _state_t::WAIT;

  // Event methods
  bool _wait_done( double t);
  bool _preplegs_done( double t);

  // State methods
  void _wait_entry();
  void _wait_during();
  void _wait_exit();

  void _preplegs_entry();
  void _preplegs_during();
  void _preplegs_exit();

  void _drawsquare_entry();
  void _drawsquare_during();
  void _drawsquare_exit();

  Eigen::Vector3d _footpos[4];
  Eigen::Vector3d _footvel[4];
  void _resetTarget();
  void _computeProfile();
  void _sendTarget();

  MdlLegControl *_legs[4];
  QuadrupedKinematics *_kinematics = nullptr;
  rtcore::Profiler *_profiler[3] = {nullptr, nullptr, nullptr};
  double _mark = 0.0;
  
  double _origin[3] = {-0.05, 0.12, -0.26};
  double _sq_period = 10;
  double _sq_xedge = 0.1;
  double _sq_yedge = 0.1;

  std::vector<Eigen::Vector3d> _fpos;
};

#endif
