# --- versionlist.toml ---
#
# Version-specific configuration values and includes

[versionconfig]
file_rev = 2              # versionlist.toml file revision
version_name = "robotv1"  # Name of the version to be checked against robotlist.toml

